/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package encarguitos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author falio
 */
public class DetallesSoliRepartidor extends javax.swing.JFrame {
    Conexion bd = new Conexion();
    Usuario u=Login.u;
    /**
     * Creates new form DetallesProdServ
     */
    public DetallesSoliRepartidor() {
        initComponents();
        try {
            if(bd.conexion.isClosed()){
                System.out.println("Noo!!!. Se cerro");
            }
        } catch (SQLException ex) {
            
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblNombre = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        LblID = new javax.swing.JLabel();
        LblNumero = new javax.swing.JLabel();
        LblPedido = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnEstado = new javax.swing.JButton();
        LblDireccion = new javax.swing.JLabel();
        LblFeEn = new javax.swing.JLabel();
        LblFeSol = new javax.swing.JLabel();
        lblFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblNombre.setText("Nombre");
        jPanel1.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volverBlack.png"))); // NOI18N
        BtnVolver.setContentAreaFilled(false);
        BtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        LblID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblID.setText("ID");
        jPanel1.add(LblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        LblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblNumero.setText("Numero");
        jPanel1.add(LblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        LblPedido.setText("Pedido");
        jPanel1.add(LblPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 330, 270));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En proceso", "Preparando envío", "Enviado", "Entregado", "Cancelado" }));
        jPanel1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        btnEstado.setText("Actualizar");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        LblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblDireccion.setText("Direccion");
        jPanel1.add(LblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        LblFeEn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblFeEn.setText("Fecha de Entrega");
        jPanel1.add(LblFeEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        LblFeSol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblFeSol.setText("Fecha de Solicitud");
        jPanel1.add(LblFeSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PlantillaMas.png"))); // NOI18N
        jPanel1.add(lblFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        ConsultarPedidosServicios cps = new ConsultarPedidosServicios();
        cps.bd=bd;
        cps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        // TODO add your handling code here:
        //actualizarProductos
        String cad=cmbEstado.getItemAt(cmbEstado.getSelectedIndex());
        if(bd.actualizarProductos(cad,u.idUsuario)){
            JOptionPane.showMessageDialog(this,"Se actualizo con exito");
        }else{
            JOptionPane.showMessageDialog(this,"Error. intenta denuevo");
        }
        
    }//GEN-LAST:event_btnEstadoActionPerformed
    public void cargarDetallesSolicitud(String[] datosSolicitud) {
    // Asignación de datos a los componentes de la interfaz
    LblNombre.setText(datosSolicitud[6]); // Nombre del cliente
    LblID.setText("ID: " + datosSolicitud[0]); // ID de la solicitud
    LblNumero.setText("Tel: " + datosSolicitud[7]); // Teléfono
    LblDireccion.setText("Dirección: " + datosSolicitud[8]); // Dirección
    
    // Formato especial para el área de pedido con HTML
    LblPedido.setText("<html><body style='width: 300px; padding: 5px;'>" +
                     "<h3>Detalles del Pedido</h3>" +
                     "<b>Tipo:</b> " + datosSolicitud[1] + "<br><br>" +
                     "<b>Especificaciones:</b><br>" + datosSolicitud[2] + "<br><br>" +
                     "<b>Estado:</b> " + datosSolicitud[5] + "<br><br>" +
                     "<b>Fecha Solicitud:</b> " + datosSolicitud[3] + "<br>" +
                     "<b>Fecha Entrega:</b> " + datosSolicitud[4] + "<br><br>" +
                     "<b>Repartidor asignado:</b> " + datosSolicitud[10] + "</body></html>");
    
    LblFeSol.setText("Solicitado: " + datosSolicitud[3]); // Fecha solicitud
    LblFeEn.setText("Entrega: " + datosSolicitud[4]); // Fecha entrega
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesSoliRepartidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesSoliRepartidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesSoliRepartidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesSoliRepartidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesSoliRepartidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel LblDireccion;
    private javax.swing.JLabel LblFeEn;
    private javax.swing.JLabel LblFeSol;
    private javax.swing.JLabel LblID;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblNumero;
    private javax.swing.JLabel LblPedido;
    private javax.swing.JButton btnEstado;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFONDO;
    // End of variables declaration//GEN-END:variables
}
