/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package encarguitos;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author falio
 */
public class PrincipalGerente extends javax.swing.JFrame {
Conexion bd = new Conexion();
public int tipoUsuario = 1;


    /**
     * Creates new form PrincipalGerente
     */
    public PrincipalGerente() {
        initComponents();
            //cargarNotificaciones(); // Agrega esta línea
        
        try {
            if(bd.conexion.isClosed()){
                System.out.println("Noo!!!. Se cerro");
            }
        } catch (SQLException ex) {
            
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public int getTipoUsuario() {
        return tipoUsuario=1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnVolver = new javax.swing.JButton();
        BtnUsuarios = new javax.swing.JButton();
        BtnClientes = new javax.swing.JButton();
        BtnPedidos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaNoti = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        BtnNotificaciones1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnVolver.setContentAreaFilled(false);
        BtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        BtnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        BtnUsuarios.setText("Usuarios");
        BtnUsuarios.setContentAreaFilled(false);
        BtnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnUsuarios.setVerifyInputWhenFocusTarget(false);
        BtnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        BtnClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        BtnClientes.setText("Clientes");
        BtnClientes.setContentAreaFilled(false);
        BtnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(BtnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 90, -1));

        BtnPedidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pedido.png"))); // NOI18N
        BtnPedidos.setText("Solicitudes");
        BtnPedidos.setContentAreaFilled(false);
        BtnPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoCarro.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 480, 120, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gerente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volverBlack.png"))); // NOI18N
        btnReset.setContentAreaFilled(false);
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, 30));

        ListaNoti.setBackground(new java.awt.Color(60, 140, 22));
        ListaNoti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ListaNoti.setForeground(new java.awt.Color(255, 255, 255));
        ListaNoti.setToolTipText("");
        jScrollPane1.setViewportView(ListaNoti);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 400, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PlantillaInterfaz.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BtnNotificaciones1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnNotificaciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notificacion.png"))); // NOI18N
        BtnNotificaciones1.setText("Notificaciones");
        BtnNotificaciones1.setContentAreaFilled(false);
        BtnNotificaciones1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNotificaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNotificaciones1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnNotificaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 537));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuariosActionPerformed
        ConsultarUsuarios CU = new ConsultarUsuarios(this.bd,this.tipoUsuario);
        CU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnUsuariosActionPerformed

    private void BtnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPedidosActionPerformed
        ConsultarPedidosServicios CP = new ConsultarPedidosServicios();
        CP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPedidosActionPerformed

    private void BtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClientesActionPerformed
        ConsultarClientes CC = new ConsultarClientes(this.bd,this.tipoUsuario);
        CC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnClientesActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
//            cargarNotificaciones();
    }//GEN-LAST:event_btnResetActionPerformed

    private void BtnNotificaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNotificaciones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNotificaciones1ActionPerformed
// Método para cargar notificaciones en el JList
/*private void cargarNotificaciones() {
    // Obtener las notificaciones de la base de datos
    ArrayList<String[]> notificaciones = bd.mostrarNotificaciones();
    
    // Crear un array para almacenar las notificaciones formateadas
    String[] notificacionesFormateadas = new String[notificaciones.size()];
    
    // Formatear cada notificación
    for (int i = 0; i < notificaciones.size(); i++) {
        String[] notificacion = notificaciones.get(i);
        notificacionesFormateadas[i] = String.format("ID: %s | Usuario: %s | Solicitud: %s | %s", 
            
            notificacion[0]  // Descripción
        );
    }
    
    // Asignar las notificaciones formateadas al JList
    ListaNoti.setListData(notificacionesFormateadas);
}*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClientes;
    private javax.swing.JButton BtnNotificaciones1;
    private javax.swing.JButton BtnPedidos;
    private javax.swing.JButton BtnUsuarios;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JList<String> ListaNoti;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
