/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package encarguitos;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author falio
 */
public class RegistrarCliente extends javax.swing.JFrame {
Conexion bd = new Conexion();
    boolean rol;//true = gerente; false = gestor

    /**
     * Creates new form RegistrarCliente
     */
    public RegistrarCliente() {
        initComponents();
        try {
            if(bd.conexion.isClosed()){
                System.out.println("Noo!!!. Se cerro");
            }
        } catch (SQLException ex) {
            
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtTel = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        TxtNomUsu = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        TxtDireccion = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        BtnRegistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TxtReferencias = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        BtnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 140, 22));
        jLabel3.setText("Nombre del Cliente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 140, 22));
        jLabel4.setText("Numero de Telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(60, 140, 22));
        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        TxtTel.setForeground(new java.awt.Color(153, 153, 153));
        TxtTel.setText("Utilice diez dígitos máximo");
        TxtTel.setBorder(null);
        TxtTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtTelMouseClicked(evt);
            }
        });
        TxtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelKeyTyped(evt);
            }
        });
        jPanel1.add(TxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 280, -1));

        jSeparator2.setForeground(new java.awt.Color(60, 140, 22));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 290, 10));

        TxtNomUsu.setForeground(new java.awt.Color(153, 153, 153));
        TxtNomUsu.setText("Ingresar Nombre de Usuario");
        TxtNomUsu.setBorder(null);
        TxtNomUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtNomUsuMouseClicked(evt);
            }
        });
        TxtNomUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNomUsuKeyTyped(evt);
            }
        });
        jPanel1.add(TxtNomUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 280, -1));

        jSeparator3.setForeground(new java.awt.Color(60, 140, 22));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 290, 10));

        TxtDireccion.setForeground(new java.awt.Color(153, 153, 153));
        TxtDireccion.setText("Direccion");
        TxtDireccion.setBorder(null);
        TxtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtDireccionMouseClicked(evt);
            }
        });
        TxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDireccionKeyTyped(evt);
            }
        });
        jPanel1.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 280, -1));

        jSeparator4.setForeground(new java.awt.Color(60, 140, 22));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 290, 10));

        BtnRegistrar.setBackground(new java.awt.Color(60, 140, 22));
        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.setToolTipText("");
        BtnRegistrar.setBorder(null);
        BtnRegistrar.setBorderPainted(false);
        BtnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(60, 140, 22));
        jLabel7.setText("Referencias");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        TxtReferencias.setForeground(new java.awt.Color(153, 153, 153));
        TxtReferencias.setText("Referencias");
        TxtReferencias.setBorder(null);
        TxtReferencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtReferenciasMouseClicked(evt);
            }
        });
        TxtReferencias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtReferenciasKeyTyped(evt);
            }
        });
        jPanel1.add(TxtReferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 280, -1));

        jSeparator5.setForeground(new java.awt.Color(60, 140, 22));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 290, 10));

        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnVolver.setContentAreaFilled(false);
        BtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrar plantilla .png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        String NombreCliente = TxtNomUsu.getText();
        String Telefono = TxtTel.getText();
        String Direccion = TxtDireccion.getText();
        String Referencias = TxtReferencias.getText();
        
        if (NombreCliente.isEmpty() || Telefono.isEmpty() || Direccion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos");
        return;
        }
        
        bd.RegistrarCliente(new Cliente(0,NombreCliente, Telefono,Direccion, Referencias ));
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void TxtNomUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNomUsuMouseClicked
        TxtNomUsu.setText("");
    }//GEN-LAST:event_TxtNomUsuMouseClicked

    private void TxtTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTelMouseClicked
        TxtTel.setText("");
    }//GEN-LAST:event_TxtTelMouseClicked

    private void TxtDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtDireccionMouseClicked
        TxtDireccion.setText("");
    }//GEN-LAST:event_TxtDireccionMouseClicked

    private void TxtReferenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtReferenciasMouseClicked
        TxtReferencias.setText("");
    }//GEN-LAST:event_TxtReferenciasMouseClicked

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
       ConsultarClientes CC = new ConsultarClientes(this.bd,0);
       CC.setVisible(true);
       this.dispose();        
          
             
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void TxtNomUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomUsuKeyTyped
        TxtNomUsu.setForeground(Color.BLACK);
    }//GEN-LAST:event_TxtNomUsuKeyTyped

    private void TxtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelKeyTyped
        TxtTel.setForeground(Color.BLACK);
    }//GEN-LAST:event_TxtTelKeyTyped

    private void TxtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionKeyTyped
        TxtDireccion.setForeground(Color.BLACK);
    }//GEN-LAST:event_TxtDireccionKeyTyped

    private void TxtReferenciasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtReferenciasKeyTyped
        TxtReferencias.setForeground(Color.BLACK);
    }//GEN-LAST:event_TxtReferenciasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtNomUsu;
    private javax.swing.JTextField TxtReferencias;
    private javax.swing.JTextField TxtTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
