/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package encarguitos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author falio
 */
public class RegistrarUsuarios extends javax.swing.JFrame {
Conexion bd = new Conexion();

    /**
     * Creates new form RegistrarUsuarios
     */
    public RegistrarUsuarios() {
        initComponents();
        try {
            if(bd.conexion.isClosed()){
                System.out.println("Noo!!!. Se cerro");
            }
        } catch (SQLException ex) {
            
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        TxtNomUs = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        TxtContrasena = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        CmbRol = new javax.swing.JComboBox<>();
        BtnRegistrar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 140, 22));
        jLabel3.setText("Nombre de Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 140, 22));
        jLabel4.setText("Correo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(60, 140, 22));
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(60, 140, 22));
        jLabel6.setText("Seleccionar Rol de Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        TxtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        TxtCorreo.setText("Ejemplo@email");
        TxtCorreo.setBorder(null);
        TxtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtCorreoMouseClicked(evt);
            }
        });
        jPanel1.add(TxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 280, -1));

        jSeparator2.setForeground(new java.awt.Color(60, 140, 22));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 290, 10));

        TxtNomUs.setForeground(new java.awt.Color(153, 153, 153));
        TxtNomUs.setText("Ingresar Nombre de Usuario");
        TxtNomUs.setBorder(null);
        TxtNomUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtNomUsMouseClicked(evt);
            }
        });
        jPanel1.add(TxtNomUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 280, -1));

        jSeparator3.setForeground(new java.awt.Color(60, 140, 22));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 290, 10));

        TxtContrasena.setForeground(new java.awt.Color(153, 153, 153));
        TxtContrasena.setText("Ingresar contraseña");
        TxtContrasena.setBorder(null);
        TxtContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtContrasenaMouseClicked(evt);
            }
        });
        jPanel1.add(TxtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 280, -1));

        jSeparator4.setForeground(new java.awt.Color(60, 140, 22));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, 10));

        CmbRol.setBackground(new java.awt.Color(60, 140, 22));
        CmbRol.setForeground(new java.awt.Color(255, 255, 255));
        CmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Gerente", "Gestor de Operaciones", "Repartidor" }));
        CmbRol.setBorder(null);
        jPanel1.add(CmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 290, -1));

        BtnRegistrar.setBackground(new java.awt.Color(60, 140, 22));
        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.setToolTipText("");
        BtnRegistrar.setBorder(null);
        BtnRegistrar.setBorderPainted(false);
        BtnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 100, 30));

        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnVolver.setContentAreaFilled(false);
        BtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrar plantilla .png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNomUsMouseClicked
        TxtNomUs.setText("");
    }//GEN-LAST:event_TxtNomUsMouseClicked

    private void TxtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCorreoMouseClicked
         TxtCorreo.setText("");
    }//GEN-LAST:event_TxtCorreoMouseClicked
  
    private void TxtContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtContrasenaMouseClicked
        TxtContrasena.setText("");
    }//GEN-LAST:event_TxtContrasenaMouseClicked

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        String NombreUsuario = TxtNomUs.getText();
        String Correo = TxtCorreo.getText();
        String Contrasena = TxtContrasena.getText();
        String Rol = CmbRol.getSelectedItem().toString();
        
        if (NombreUsuario.isEmpty() || Correo.isEmpty() || Contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos");
        return;
        }
        
        bd.RegistrarUsuario(new Usuario(0,NombreUsuario,Correo, Contrasena, Rol));
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
       ConsultarUsuarios CU = new ConsultarUsuarios(this.bd,0);
       CU.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JComboBox<String> CmbRol;
    private javax.swing.JTextField TxtContrasena;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtNomUs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
